services:
  postgres:
    image: postgres
    container_name: xsis_test
    ports: 
      - 6500:5432
    env_file:
      - ./app.env    
    volumes:
      - postgres:/val/lib/postgresql/data
volumes:
  postgres:
